# https://help.github.com/en/github/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions
# https://github.com/marketplace/actions/gradle-command
name: Publish plugins
on:
  push:
    paths:
      - 'plugins/version.txt'
    branches:
      - main
jobs:
  gradle-plugins-publishing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - uses: eskatos/gradle-command-action@v1
        with:
          wrapper-directory: plugins
          build-root-directory: plugins
          arguments: publishToAppropriateRepo --scan -Pgradle.publish.key=${{ secrets.gradle_publish_key }} -Pgradle.publish.secret=${{ secrets.gradle_publish_secret }}
        env:
          sonatype_username: ${{ secrets.SONATYPE_USERNAME }}
          sonatype_password: ${{ secrets.SONATYPE_PASSWORD }}
          GPG_key_id: ${{ secrets.GPG_KEY_ID }}
          GPG_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          GPG_private_password: ${{ secrets.GPG_PRIVATE_PASSWORD }}
